const foodProducts = [
  {
    id: 1,
    name: "Classic Pancakes",
    price: 80,
    rating: 4.5,
    description: "Start your day with a stack of fluffy pancakes served with maple syrup and butter.",
    category: "Breakfast",
    imageUrl: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=480&auto=format&fit=crop",
    tags: ["sweet", "breakfast classic", "vegetarian"],
    calories: 450,
    preparationTime: "15 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 2,
    name: "Egg and Bacon Croissant",
    price: 110,
    rating: 4.2,
    description: "Indulge in a buttery croissant filled with scrambled eggs, crispy bacon, and melted cheese.",
    category: "Breakfast",
    imageUrl: "https://images.unsplash.com/photo-1600336153113-d66c79de3e91?w=480&auto=format&fit=crop",
    tags: ["savory", "breakfast sandwich", "protein"],
    calories: 520,
    preparationTime: "10 min",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 3,
    name: "Greek Yogurt Parfait",
    price: 95,
    rating: 4.1,
    description: "Enjoy a healthy and refreshing breakfast with layers of Greek yogurt, fresh berries, and crunchy granola.",
    category: "Breakfast",
    imageUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=480&auto=format&fit=crop",
    tags: ["healthy", "fruit", "protein"],
    calories: 320,
    preparationTime: "5 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 4,
    name: "Avocado Toast",
    price: 120,
    rating: 4.6,
    description: "Savor the creaminess of mashed avocado on toasted artisan bread, topped with cherry tomatoes and microgreens.",
    category: "Breakfast",
    imageUrl: "https://images.unsplash.com/photo-1588137378133-f5496401d5d9?w=480&auto=format&fit=crop",
    tags: ["healthy", "trendy", "vegetarian"],
    calories: 380,
    preparationTime: "10 min",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false
  },
  {
    id: 5,
    name: "Fruit and Nut Oatmeal",
    price: 85,
    rating: 4.5,
    description: "Warm up with a bowl of hearty oatmeal packed with mixed nuts, dried fruits, and a drizzle of honey.",
    category: "Breakfast",
    imageUrl: "https://images.unsplash.com/photo-1517673132405-a56a62b18caf?w=480&auto=format&fit=crop",
    tags: ["healthy", "fiber", "warm"],
    calories: 410,
    preparationTime: "12 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 6,
    name: "Eggs Benedict",
    price: 140,
    rating: 4.7,
    description: "A brunch favorite featuring poached eggs on English muffins with Canadian bacon and rich hollandaise sauce.",
    category: "Breakfast",
    imageUrl: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=480&auto=format&fit=crop",
    tags: ["gourmet", "brunch", "classic"],
    calories: 650,
    preparationTime: "20 min",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 7,
    name: "Blueberry Muffins",
    price: 75,
    rating: 4.3,
    description: "Moist and fluffy muffins bursting with fresh blueberries, topped with a crunchy streusel topping.",
    category: "Bakery",
    imageUrl: "https://images.unsplash.com/photo-1599420186946-7b6fb4e297f0?w=480&auto=format&fit=crop",
    tags: ["sweet", "bakery", "fruit"],
    calories: 320,
    preparationTime: "25 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 8,
    name: "Breakfast Burrito",
    price: 130,
    rating: 4.4,
    description: "A hearty wrap filled with scrambled eggs, black beans, cheese, avocado, and spicy salsa.",
    category: "Breakfast",
    imageUrl: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=480&auto=format&fit=crop",
    tags: ["filling", "mexican-inspired", "protein"],
    calories: 580,
    preparationTime: "15 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 9,
    name: "Smoked Salmon Bagel",
    price: 160,
    rating: 4.5,
    description: "Fresh bagel topped with cream cheese, smoked salmon, capers, red onion, and dill.",
    category: "Breakfast",
    imageUrl: "https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=480&auto=format&fit=crop",
    tags: ["seafood", "gourmet", "high-protein"],
    calories: 480,
    preparationTime: "5 min",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 10,
    name: "Vegetable Frittata",
    price: 115,
    rating: 4.2,
    description: "Italian-style open-faced omelet loaded with seasonal vegetables and melted cheese.",
    category: "Breakfast",
    imageUrl: "https://images.unsplash.com/photo-1623428454614-abaf7c224d31?w=480&auto=format&fit=crop",
    tags: ["vegetarian", "low-carb", "protein"],
    calories: 390,
    preparationTime: "25 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 11,
    name: "French Toast",
    price: 95,
    rating: 4.4,
    description: "Thick slices of brioche bread soaked in vanilla-cinnamon egg batter, grilled to perfection, and dusted with powdered sugar.",
    category: "Breakfast",
    imageUrl: "https://images.unsplash.com/photo-1639108094328-2b94a49b1c2e?w=480&auto=format&fit=crop",
    tags: ["sweet", "classic", "indulgent"],
    calories: 420,
    preparationTime: "15 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 12,
    name: "Chicken Caesar Salad",
    price: 135,
    rating: 4.3,
    description: "Crisp romaine lettuce tossed with grilled chicken, Parmesan cheese, croutons, and creamy Caesar dressing.",
    category: "Salads",
    imageUrl: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=480&auto=format&fit=crop",
    tags: ["lunch", "protein", "classic"],
    calories: 380,
    preparationTime: "15 min",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 13,
    name: "Margherita Pizza",
    price: 140,
    rating: 4.6,
    description: "Classic thin-crust pizza topped with tomato sauce, fresh mozzarella, basil leaves, and a drizzle of olive oil.",
    category: "Mains",
    imageUrl: "https://images.unsplash.com/photo-1604917877934-c92f4578f3c7?w=480&auto=format&fit=crop",
    tags: ["italian", "vegetarian", "classic"],
    calories: 850,
    preparationTime: "20 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 14,
    name: "Beef Burger",
    price: 150,
    rating: 4.5,
    description: "Juicy beef patty on a toasted brioche bun with lettuce, tomato, cheese, and special house sauce.",
    category: "Mains",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=480&auto=format&fit=crop",
    tags: ["burgers", "american", "beef"],
    calories: 780,
    preparationTime: "18 min",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 15,
    name: "Caprese Sandwich",
    price: 125,
    rating: 4.2,
    description: "Fresh mozzarella, ripe tomatoes, and basil leaves with balsamic glaze on ciabatta bread.",
    category: "Sandwiches",
    imageUrl: "https://images.unsplash.com/photo-1628294895950-9805252673c6?w=480&auto=format&fit=crop",
    tags: ["italian", "vegetarian", "lunch"],
    calories: 420,
    preparationTime: "10 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false
  },
  // Continuing with more products...
  {
    id: 16,
    name: "Mushroom Risotto",
    price: 160,
    rating: 4.4,
    description: "Creamy Arborio rice slowly cooked with a medley of wild mushrooms, white wine, and Parmesan cheese.",
    category: "Mains",
    imageUrl: "https://images.unsplash.com/photo-1633964913295-ceb43826e7c1?w=480&auto=format&fit=crop",
    tags: ["italian", "vegetarian", "creamy"],
    calories: 580,
    preparationTime: "30 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 17,
    name: "Grilled Salmon",
    price: 195,
    rating: 4.7,
    description: "Fresh Atlantic salmon fillet grilled to perfection, served with steamed vegetables and lemon-dill sauce.",
    category: "Mains",
    imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=480&auto=format&fit=crop",
    tags: ["seafood", "healthy", "protein"],
    calories: 420,
    preparationTime: "20 min",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 18,
    name: "Chocolate Lava Cake",
    price: 90,
    rating: 4.8,
    description: "Decadent chocolate cake with a warm, flowing chocolate center, served with vanilla ice cream.",
    category: "Desserts",
    imageUrl: "https://images.unsplash.com/photo-1617305855058-336d9ce3eb56?w=480&auto=format&fit=crop",
    tags: ["chocolate", "indulgent", "hot"],
    calories: 450,
    preparationTime: "15 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 19,
    name: "Vegetable Stir Fry",
    price: 130,
    rating: 4.3,
    description: "Colorful assortment of crisp vegetables stir-fried with ginger, garlic, and soy sauce, served over steamed rice.",
    category: "Mains",
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=480&auto=format&fit=crop",
    tags: ["asian", "vegetarian", "healthy"],
    calories: 380,
    preparationTime: "15 min",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true
  },
  {
    id: 20,
    name: "Spaghetti Carbonara",
    price: 145,
    rating: 4.6,
    description: "Classic Italian pasta tossed with crispy pancetta, eggs, Pecorino Romano cheese, and freshly ground black pepper.",
    category: "Mains",
    imageUrl: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=480&auto=format&fit=crop",
    tags: ["italian", "pasta", "creamy"],
    calories: 720,
    preparationTime: "20 min",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false
  },
  
  // Adding more products to reach close to 200...
  // I'll create about 20 more for the sample and indicate where to continue
  
  {
    id: 21,
    name: "Acai Bowl",
    price: 120,
    rating: 4.5,
    description: "Refreshing blend of acai berries topped with granola, fresh fruits, coconut flakes, and a drizzle of honey.",
    category: "Breakfast",
    imageUrl: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=480&auto=format&fit=crop",
    tags: ["healthy", "superfood", "fruit"],
    calories: 340,
    preparationTime: "10 min",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true
  },
  {
    id: 22,
    name: "Beef Tacos",
    price: 135,
    rating: 4.4,
    description: "Three soft corn tortillas filled with seasoned ground beef, fresh salsa, guacamole, and shredded cheese.",
    category: "Mains",
    imageUrl: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=480&auto=format&fit=crop",
    tags: ["mexican", "beef", "spicy"],
    calories: 520,
    preparationTime: "20 min",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 23,
    name: "Mango Smoothie",
    price: 85,
    rating: 4.3,
    description: "Tropical blend of fresh mango, yogurt, and honey, topped with chia seeds and mango chunks.",
    category: "Drinks",
    imageUrl: "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=480&auto=format&fit=crop",
    tags: ["refreshing", "fruit", "cold"],
    calories: 260,
    preparationTime: "5 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 24,
    name: "Pad Thai",
    price: 150,
    rating: 4.5,
    description: "Traditional Thai stir-fried rice noodles with tofu, bean sprouts, eggs, and peanuts in a tangy tamarind sauce.",
    category: "Mains",
    imageUrl: "https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=480&auto=format&fit=crop",
    tags: ["thai", "noodles", "stir-fry"],
    calories: 550,
    preparationTime: "25 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 25,
    name: "Iced Coffee",
    price: 65,
    rating: 4.2,
    description: "Smooth cold brew coffee served over ice with a splash of milk and optional flavored syrup.",
    category: "Drinks",
    imageUrl: "https://images.unsplash.com/photo-1578314675229-985f5e5da8a5?w=480&auto=format&fit=crop",
    tags: ["coffee", "cold", "caffeinated"],
    calories: 120,
    preparationTime: "3 min",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true
  },
  {
    id: 26,
    name: "Lobster Roll",
    price: 210,
    rating: 4.8,
    description: "Fresh Maine lobster meat tossed with light mayo, lemon, and herbs in a buttered and toasted split-top roll.",
    category: "Sandwiches",
    imageUrl: "https://images.unsplash.com/photo-1559132250-0a1eb8b93946?w=480&auto=format&fit=crop",
    tags: ["seafood", "gourmet", "summer"],
    calories: 480,
    preparationTime: "15 min",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 27,
    name: "Quinoa Salad",
    price: 125,
    rating: 4.2,
    description: "Protein-rich quinoa tossed with cucumber, cherry tomatoes, red onions, and feta cheese in a lemon vinaigrette.",
    category: "Salads",
    imageUrl: "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=480&auto=format&fit=crop",
    tags: ["healthy", "protein", "vegetarian"],
    calories: 320,
    preparationTime: "25 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 28,
    name: "Beef Pho",
    price: 140,
    rating: 4.6,
    description: "Vietnamese rice noodle soup with thinly sliced beef, aromatic herbs, and rich bone broth.",
    category: "Soups",
    imageUrl: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=480&auto=format&fit=crop",
    tags: ["vietnamese", "soup", "comfort food"],
    calories: 490,
    preparationTime: "30 min",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 29,
    name: "Apple Pie",
    price: 85,
    rating: 4.5,
    description: "Classic American dessert with spiced apple filling in a flaky, buttery crust, served with vanilla ice cream.",
    category: "Desserts",
    imageUrl: "https://images.unsplash.com/photo-1568571780765-9276a958bdb4?w=480&auto=format&fit=crop",
    tags: ["dessert", "american", "classic"],
    calories: 410,
    preparationTime: "50 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 30,
    name: "Falafel Wrap",
    price: 115,
    rating: 4.3,
    description: "Crispy chickpea patties wrapped in warm pita with tahini sauce, lettuce, tomatoes, and pickles.",
    category: "Sandwiches",
    imageUrl: "https://images.unsplash.com/photo-1642783944285-b33b18effb34?w=480&auto=format&fit=crop",
    tags: ["middle eastern", "vegetarian", "protein"],
    calories: 460,
    preparationTime: "15 min",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false
  }, 
  {
    id: 31,
    name: "Matcha Green Tea Latte",
    price: 95,
    rating: 4.3,
    description: "Smooth and earthy matcha green tea powder whisked with steamed milk, lightly sweetened for a calming beverage.",
    category: "Drinks",
    imageUrl: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=480&auto=format&fit=crop",
    tags: ["japanese", "tea", "antioxidant"],
    calories: 180,
    preparationTime: "5 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 32,
    name: "Mediterranean Hummus Platter",
    price: 130,
    rating: 4.4,
    description: "Creamy housemade hummus served with warm pita bread, cucumber slices, olives, and roasted red peppers.",
    category: "Appetizers",
    imageUrl: "https://images.unsplash.com/photo-1553632958-1666bf30c5b3?w=480&auto=format&fit=crop",
    tags: ["middle eastern", "sharing", "healthy"],
    calories: 420,
    preparationTime: "10 min",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false
  },
  {
    id: 33,
    name: "Thai Green Curry",
    price: 155,
    rating: 4.6,
    description: "Fragrant coconut milk curry with bamboo shoots, bell peppers, and your choice of chicken or tofu, served with jasmine rice.",
    category: "Mains",
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=480&auto=format&fit=crop",
    tags: ["thai", "spicy", "aromatic"],
    calories: 650,
    preparationTime: "25 min",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 34,
    name: "Tiramisu",
    price: 90,
    rating: 4.7,
    description: "Classic Italian dessert with layers of espresso-soaked ladyfingers and mascarpone cream, dusted with cocoa powder.",
    category: "Desserts",
    imageUrl: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=480&auto=format&fit=crop",
    tags: ["italian", "coffee", "creamy"],
    calories: 380,
    preparationTime: "15 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 35,
    name: "Chicken Tikka Masala",
    price: 165,
    rating: 4.8,
    description: "Tender chicken pieces marinated in yogurt and spices, grilled and simmered in a rich tomato-based curry sauce.",
    category: "Mains",
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=480&auto=format&fit=crop",
    tags: ["indian", "curry", "spicy"],
    calories: 580,
    preparationTime: "30 min",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 36,
    name: "Spinach and Feta Stuffed Mushrooms",
    price: 110,
    rating: 4.2,
    description: "Large portobello mushrooms filled with a savory mixture of spinach, feta cheese, and herbs, topped with crispy breadcrumbs.",
    category: "Appetizers",
    imageUrl: "https://images.unsplash.com/photo-1574484249203-7b4a0c43af15?w=480&auto=format&fit=crop",
    tags: ["vegetarian", "appetizer", "savory"],
    calories: 280,
    preparationTime: "20 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 37,
    name: "Cold Brew Coffee",
    price: 75,
    rating: 4.5,
    description: "Smooth, low-acid coffee steeped for 24 hours and served over ice, perfect for a refreshing caffeine boost.",
    category: "Drinks",
    imageUrl: "https://images.unsplash.com/photo-1592663527359-cf6642f54cff?w=480&auto=format&fit=crop",
    tags: ["coffee", "refreshing", "cold"],
    calories: 15,
    preparationTime: "2 min",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true
  },
  {
    id: 38,
    name: "Vegetable Biryani",
    price: 145,
    rating: 4.3,
    description: "Fragrant basmati rice cooked with mixed vegetables, saffron, and aromatic spices, garnished with fried onions and mint.",
    category: "Mains",
    imageUrl: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=480&auto=format&fit=crop",
    tags: ["indian", "rice", "aromatic"],
    calories: 520,
    preparationTime: "35 min",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true
  },
  {
    id: 39,
    name: "Fish and Chips",
    price: 155,
    rating: 4.4,
    description: "Crispy beer-battered cod served with thick-cut fries, tartar sauce, and malt vinegar.",
    category: "Mains",
    imageUrl: "https://images.unsplash.com/photo-1579208030886-b937da9925dc?w=480&auto=format&fit=crop",
    tags: ["british", "seafood", "comfort food"],
    calories: 850,
    preparationTime: "20 min",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 40,
    name: "Berry Cheesecake",
    price: 95,
    rating: 4.7,
    description: "Smooth and creamy New York-style cheesecake topped with a mixed berry compote and fresh berries.",
    category: "Desserts",
    imageUrl: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=480&auto=format&fit=crop",
    tags: ["dessert", "creamy", "berries"],
    calories: 450,
    preparationTime: "20 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 41,
    name: "Shrimp Scampi Pasta",
    price: 175,
    rating: 4.6,
    description: "Succulent shrimp sautéed with garlic, white wine, lemon, and chili flakes, tossed with al dente linguine.",
    category: "Mains",
    imageUrl: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=480&auto=format&fit=crop",
    tags: ["italian", "seafood", "pasta"],
    calories: 620,
    preparationTime: "25 min",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 42,
    name: "Lentil Soup",
    price: 95,
    rating: 4.1,
    description: "Hearty and nutritious soup made with red lentils, vegetables, and aromatic spices, served with crusty bread.",
    category: "Soups",
    imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=480&auto=format&fit=crop",
    tags: ["healthy", "vegetarian", "comfort food"],
    calories: 320,
    preparationTime: "30 min",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true
  },
  {
    id: 43,
    name: "Pulled Pork Sandwich",
    price: 140,
    rating: 4.5,
    description: "Slow-cooked tender pulled pork tossed in BBQ sauce, topped with coleslaw and served on a brioche bun.",
    category: "Sandwiches",
    imageUrl: "https://images.unsplash.com/photo-1580622304679-148a8f896076?w=480&auto=format&fit=crop",
    tags: ["bbq", "american", "meat"],
    calories: 680,
    preparationTime: "15 min",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 44,
    name: "Greek Salad",
    price: 120,
    rating: 4.3,
    description: "Crisp cucumbers, juicy tomatoes, red onions, olives, and feta cheese tossed in olive oil and oregano dressing.",
    category: "Salads",
    imageUrl: "https://images.unsplash.com/photo-1551248429-40975aa4de74?w=480&auto=format&fit=crop",
    tags: ["greek", "fresh", "healthy"],
    calories: 310,
    preparationTime: "10 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 45,
    name: "Truffle Fries",
    price: 95,
    rating: 4.6,
    description: "Crispy golden fries tossed with truffle oil, Parmesan cheese, and fresh herbs.",
    category: "Sides",
    imageUrl: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=480&auto=format&fit=crop",
    tags: ["indulgent", "shareable", "gourmet"],
    calories: 420,
    preparationTime: "15 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 46,
    name: "Coconut Panna Cotta",
    price: 85,
    rating: 4.2,
    description: "Silky coconut milk custard set with gelatin, topped with tropical fruit compote and toasted coconut flakes.",
    category: "Desserts",
    imageUrl: "https://images.unsplash.com/photo-1624300603538-1840de7f4171?w=480&auto=format&fit=crop",
    tags: ["dessert", "tropical", "italian"],
    calories: 310,
    preparationTime: "10 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 47,
    name: "Beet and Goat Cheese Salad",
    price: 130,
    rating: 4.4,
    description: "Roasted beets, creamy goat cheese, and candied walnuts on a bed of mixed greens with balsamic vinaigrette.",
    category: "Salads",
    imageUrl: "https://images.unsplash.com/photo-1551248429-40975aa4de74?w=480&auto=format&fit=crop",
    tags: ["healthy", "vegetarian", "gourmet"],
    calories: 350,
    preparationTime: "15 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 48,
    name: "Eggplant Parmesan",
    price: 135,
    rating: 4.2,
    description: "Layers of breaded eggplant, marinara sauce, and melted mozzarella and parmesan cheeses, baked until bubbly.",
    category: "Mains",
    imageUrl: "https://images.unsplash.com/photo-1625944228741-aa4ac42697ac?w=480&auto=format&fit=crop",
    tags: ["italian", "vegetarian", "comfort food"],
    calories: 520,
    preparationTime: "35 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 49,
    name: "Buffalo Chicken Wings",
    price: 125,
    rating: 4.5,
    description: "Crispy chicken wings tossed in spicy buffalo sauce, served with blue cheese dip, celery and carrot sticks.",
    category: "Appetizers",
    imageUrl: "https://images.unsplash.com/photo-1608039755401-742074f0548d?w=480&auto=format&fit=crop",
    tags: ["spicy", "american", "shareable"],
    calories: 650,
    preparationTime: "20 min",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 50,
    name: "Miso Ramen",
    price: 145,
    rating: 4.7,
    description: "Hearty ramen noodles in a rich miso broth with char siu pork, soft-boiled egg, corn, bamboo shoots, and green onions.",
    category: "Soups",
    imageUrl: "https://images.unsplash.com/photo-1557872943-16a5ac26437e?w=480&auto=format&fit=crop",
    tags: ["japanese", "noodles", "comfort food"],
    calories: 680,
    preparationTime: "20 min",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 51,
    name: "Strawberry Shortcake",
    price: 90,
    rating: 4.4,
    description: "Classic dessert featuring light, sweet biscuits layered with fresh strawberries and whipped cream.",
    category: "Desserts",
    imageUrl: "https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81?w=480&auto=format&fit=crop",
    tags: ["dessert", "fruit", "classic"],
    calories: 380,
    preparationTime: "15 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 52,
    name: "Vegetable Spring Rolls",
    price: 85,
    rating: 4.1,
    description: "Crispy fried rolls filled with cabbage, carrots, mushrooms, and bean sprouts, served with sweet chili dipping sauce.",
    category: "Appetizers",
    imageUrl: "https://images.unsplash.com/photo-1603024468676-75fdffa62a63?w=480&auto=format&fit=crop",
    tags: ["asian", "vegetarian", "crispy"],
    calories: 280,
    preparationTime: "15 min",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false
  },
  {
    id: 53,
    name: "Hawaiian Poke Bowl",
    price: 160,
    rating: 4.6,
    description: "Fresh diced raw tuna marinated in soy sauce and sesame oil, served over rice with avocado, cucumber, and seaweed.",
    category: "Mains",
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=480&auto=format&fit=crop",
    tags: ["hawaiian", "seafood", "healthy"],
    calories: 450,
    preparationTime: "10 min",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 54,
    name: "Butternut Squash Soup",
    price: 90,
    rating: 4.3,
    description: "Creamy, velvety soup made with roasted butternut squash, onions, and herbs, garnished with pumpkin seeds and crème fraîche.",
    category: "Soups",
    imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=480&auto=format&fit=crop",
    tags: ["seasonal", "vegetarian", "comfort food"],
    calories: 290,
    preparationTime: "25 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 55,
    name: "BBQ Pulled Jackfruit Burger",
    price: 135,
    rating: 4.2,
    description: "Plant-based burger featuring tender pulled jackfruit in smoky BBQ sauce, topped with coleslaw on a vegan bun.",
    category: "Sandwiches",
    imageUrl: "https://images.unsplash.com/photo-1520072959219-c595dc870360?w=480&auto=format&fit=crop",
    tags: ["vegan", "plant-based", "bbq"],
    calories: 420,
    preparationTime: "15 min",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false
  },
  {
    id: 56,
    name: "Lamb Kebabs",
    price: 175,
    rating: 4.6,
    description: "Tender pieces of marinated lamb skewered with bell peppers and onions, grilled to perfection and served with tzatziki sauce.",
    category: "Mains",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=480&auto=format&fit=crop",
    tags: ["mediterranean", "grilled", "protein"],
    calories: 480,
    preparationTime: "25 min",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 57,
    name: "Raspberry Cheesecake Brownie",
    price: 95,
    rating: 4.8,
    description: "Decadent chocolate brownie topped with creamy cheesecake and swirls of raspberry sauce.",
    category: "Desserts",
    imageUrl: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=480&auto=format&fit=crop",
    tags: ["dessert", "chocolate", "fusion"],
    calories: 410,
    preparationTime: "15 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false
  },
  {
    id: 58,
    name: "Tuna Niçoise Salad",
    price: 145,
    rating: 4.4,
    description: "Classic French salad with seared tuna, boiled eggs, green beans, potatoes, olives, and tomatoes in Dijon vinaigrette.",
    category: "Salads",
    imageUrl: "https://images.unsplash.com/photo-1551248429-40975aa4de74?w=480&auto=format&fit=crop",
    tags: ["french", "seafood", "protein"],
    calories: 380,
    preparationTime: "20 min",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 59,
    name: "Mushroom and Truffle Risotto",
    price: 170,
    rating: 4.7,
    description: "Creamy Arborio rice slowly cooked with wild mushrooms, finished with truffle oil and shaved Parmesan.",
    category: "Mains",
    imageUrl: "https://images.unsplash.com/photo-1633964913295-ceb43826e7c1?w=480&auto=format&fit=crop",
    tags: ["italian", "gourmet", "vegetarian"],
    calories: 610,
    preparationTime: "30 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true
  },
  {
    id: 60,
    name: "Sweet Potato Fries",
    price: 80,
    rating: 4.3,
    description: "Crispy baked sweet potato fries seasoned with paprika and served with chipotle aioli dipping sauce.",
    category: "Sides",
    imageUrl: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=480&auto=format&fit=crop",
    tags: ["healthy", "vegetarian", "snack"],
    calories: 320,
    preparationTime: "20 min",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true
  },
  {
     id: 61,
     name: "Korean Fried Chicken",
     price: 150,
     rating: 4.7,
     description: "Crispy twice-fried chicken tossed in a sweet and spicy gochujang sauce, garnished with sesame seeds and green onions.",
     category: "Mains",
     imageUrl: "https://images.unsplash.com/photo-1585703900468-13c7a978ad86?w=480&auto=format&fit=crop",
     tags: ["korean", "spicy", "crispy"],
     calories: 720,
     preparationTime: "25 min",
     isVegetarian: false,
     isVegan: false,
     isGlutenFree: true
   },
   {
     id: 62,
     name: "Açaí Smoothie Bowl",
     price: 125,
     rating: 4.4,
     description: "Thick smoothie base made with açaí berries topped with sliced banana, granola, chia seeds, and a drizzle of honey.",
     category: "Breakfast",
     imageUrl: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=480&auto=format&fit=crop",
     tags: ["healthy", "superfood", "breakfast"],
     calories: 380,
     preparationTime: "8 min",
     isVegetarian: true,
     isVegan: true,
     isGlutenFree: true
   },
   {
     id: 63,
     name: "Wild Mushroom Flatbread",
     price: 135,
     rating: 4.3,
     description: "Artisanal flatbread topped with assorted wild mushrooms, caramelized onions, truffle oil, and fresh thyme.",
     category: "Appetizers",
     imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=480&auto=format&fit=crop",
     tags: ["vegetarian", "gourmet", "sharing"],
     calories: 410,
     preparationTime: "15 min",
     isVegetarian: true,
     isVegan: false,
     isGlutenFree: false
   },
   {
     id: 64,
     name: "Beef Wellington",
     price: 280,
     rating: 4.9,
     description: "Tender filet mignon coated with mushroom duxelles and wrapped in puff pastry, baked to golden perfection.",
     category: "Mains",
     imageUrl: "https://images.unsplash.com/photo-1625944461209-504e5f7e0eb8?w=480&auto=format&fit=crop",
     tags: ["gourmet", "british", "special occasion"],
     calories: 850,
     preparationTime: "45 min",
     isVegetarian: false,
     isVegan: false,
     isGlutenFree: false
   },
   {
     id: 65,
     name: "Lemon Blueberry Pancakes",
     price: 110,
     rating: 4.5,
     description: "Fluffy pancakes infused with lemon zest, studded with fresh blueberries and topped with lemon curd and maple syrup.",
     category: "Breakfast",
     imageUrl: "https://images.unsplash.com/photo-1495147466023-ac5c588e2e94?w=480&auto=format&fit=crop",
     tags: ["sweet", "breakfast", "fruit"],
     calories: 520,
     preparationTime: "18 min",
     isVegetarian: true,
     isVegan: false,
     isGlutenFree: false
   },
   {
     id: 66,
     name: "Seafood Paella",
     price: 195,
     rating: 4.6,
     description: "Traditional Spanish rice dish cooked with saffron, shrimp, mussels, clams, and chorizo in a rich seafood broth.",
     category: "Mains",
     imageUrl: "https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=480&auto=format&fit=crop",
     tags: ["spanish", "seafood", "rice"],
     calories: 690,
     preparationTime: "40 min",
     isVegetarian: false,
     isVegan: false,
     isGlutenFree: true
   },
   {
     id: 67,
     name: "Watermelon Feta Salad",
     price: 115,
     rating: 4.2,
     description: "Refreshing combination of juicy watermelon cubes, crumbled feta cheese, fresh mint, and a light balsamic glaze.",
     category: "Salads",
     imageUrl: "https://images.unsplash.com/photo-1563252592-8a8ebd0aec26?w=480&auto=format&fit=crop",
     tags: ["summer", "refreshing", "light"],
     calories: 230,
     preparationTime: "10 min",
     isVegetarian: true,
     isVegan: false,
     isGlutenFree: true
   },
   {
     id: 68,
     name: "Churros with Chocolate Sauce",
     price: 85,
     rating: 4.7,
     description: "Crispy Spanish fried dough pastries coated in cinnamon sugar, served with a rich dark chocolate dipping sauce.",
     category: "Desserts",
     imageUrl: "https://images.unsplash.com/photo-1536585531404-b46e330c1b9a?w=480&auto=format&fit=crop",
     tags: ["spanish", "fried", "sweet"],
     calories: 420,
     preparationTime: "20 min",
     isVegetarian: true,
     isVegan: false,
     isGlutenFree: false
   },
   {
     id: 69,
     name: "Loaded Nachos",
     price: 125,
     rating: 4.4,
     description: "Crispy tortilla chips topped with melted cheese, black beans, jalapeños, guacamole, sour cream, and pico de gallo.",
     category: "Appetizers",
     imageUrl: "https://images.unsplash.com/photo-1582169296194-e4d644c48063?w=480&auto=format&fit=crop",
     tags: ["mexican", "sharing", "spicy"],
     calories: 780,
     preparationTime: "15 min",
     isVegetarian: true,
     isVegan: false,
     isGlutenFree: true
   },
   {
     id: 70,
     name: "Vietnamese Banh Mi",
     price: 120,
     rating: 4.5,
     description: "Crusty baguette filled with pickled vegetables, cilantro, jalapeños, and your choice of grilled pork or tofu with spicy mayo.",
     category: "Sandwiches",
     imageUrl: "https://images.unsplash.com/photo-1588170767449-394732e6b932?w=480&auto=format&fit=crop",
     tags: ["vietnamese", "sandwich", "fusion"],
     calories: 480,
     preparationTime: "12 min",
     isVegetarian: false,
     isVegan: false,
     isGlutenFree: false
   },
   {
     id: 71,
     name: "Pistachio Rosewater Cake",
     price: 95,
     rating: 4.6,
     description: "Delicate sponge cake infused with rosewater, layered with pistachio buttercream and topped with crushed pistachios.",
     category: "Desserts",
     imageUrl: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=480&auto=format&fit=crop",
     tags: ["middle eastern", "elegant", "sweet"],
     calories: 380,
     preparationTime: "20 min",
     isVegetarian: true,
     isVegan: false,
     isGlutenFree: false
   },
   {
     id: 72,
     name: "Roasted Brussels Sprouts",
     price: 90,
     rating: 4.2,
     description: "Crispy roasted Brussels sprouts tossed with balsamic glaze, bacon bits, and toasted pine nuts.",
     category: "Sides",
     imageUrl: "https://images.unsplash.com/photo-1584270354949-c26b0d5b4a0c?w=480&auto=format&fit=crop",
     tags: ["vegetables", "roasted", "side dish"],
     calories: 240,
     preparationTime: "20 min",
     isVegetarian: false,
     isVegan: false,
     isGlutenFree: true
   },
   {
     id: 73,
     name: "Turmeric Latte",
     price: 75,
     rating: 4.3,
     description: "Warming beverage made with steamed milk, turmeric, ginger, cinnamon, and honey for a comforting anti-inflammatory drink.",
     category: "Drinks",
     imageUrl: "https://images.unsplash.com/photo-1578598336012-83231c981b2a?w=480&auto=format&fit=crop",
     tags: ["healthy", "warm", "anti-inflammatory"],
     calories: 180,
     preparationTime: "5 min",
     isVegetarian: true,
     isVegan: false,
     isGlutenFree: true
   },
   {
     id: 74,
     name: "Shakshuka",
     price: 125,
     rating: 4.6,
     description: "Middle Eastern dish of eggs poached in a spiced tomato and red pepper sauce, topped with feta and herbs.",
     category: "Breakfast",
     imageUrl: "https://images.unsplash.com/photo-1582149509900-3d0574bcbfb4?w=480&auto=format&fit=crop",
     tags: ["middle eastern", "eggs", "savory"],
     calories: 410,
     preparationTime: "25 min",
     isVegetarian: true,
     isVegan: false,
     isGlutenFree: true
   },
   {
     id: 75,
     name: "Honey Sriracha Glazed Salmon",
     price: 185,
     rating: 4.7,
     description: "Fresh salmon fillet glazed with sweet and spicy honey sriracha sauce, served with steamed vegetables.",
     category: "Mains",
     imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=480&auto=format&fit=crop",
     tags: ["seafood", "sweet and spicy", "high-protein"],
     calories: 450,
     preparationTime: "22 min",
     isVegetarian: false,
     isVegan: false,
     isGlutenFree: true
   },
   {
     id: 76,
     name: "Garlic Parmesan Zucchini Fries",
     price: 85,
     rating: 4.1,
     description: "Crispy baked zucchini sticks coated in a garlic parmesan breadcrumb mixture, served with marinara sauce.",
     category: "Appetizers",
     imageUrl: "https://images.unsplash.com/photo-1603964555825-90481f35aaab?w=480&auto=format&fit=crop",
     tags: ["vegetables", "baked", "snack"],
     calories: 270,
     preparationTime: "25 min",
     isVegetarian: true,
     isVegan: false,
     isGlutenFree: false
   },
   {
     id: 77,
     name: "Mango Sticky Rice",
     price: 90,
     rating: 4.5,
     description: "Sweet Thai dessert featuring sticky rice infused with coconut milk, served with fresh mango slices.",
     category: "Desserts",
     imageUrl: "https://images.unsplash.com/photo-1561668048-fe9c092844eb?w=480&auto=format&fit=crop",
     tags: ["thai", "tropical", "sweet"],
     calories: 350,
     preparationTime: "30 min",
     isVegetarian: true,
     isVegan: true,
     isGlutenFree: true
   },
   {
     id: 78,
     name: "Mediterranean Grilled Octopus",
     price: 190,
     rating: 4.8,
     description: "Tender grilled octopus marinated in olive oil, lemon, and herbs, served with crispy potatoes and garlic aioli.",
     category: "Mains",
     imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=480&auto=format&fit=crop",
     tags: ["mediterranean", "seafood", "grilled"],
     calories: 420,
     preparationTime: "35 min",
     isVegetarian: false,
     isVegan: false,
     isGlutenFree: true
   },
   {
     id: 79,
     name: "Pesto Pasta Salad",
     price: 120,
     rating: 4.2,
     description: "Chilled pasta tossed with fresh basil pesto, cherry tomatoes, mozzarella pearls, and pine nuts.",
     category: "Salads",
     imageUrl: "https://images.unsplash.com/photo-1551248429-40975aa4de74?w=480&auto=format&fit=crop",
     tags: ["italian", "cold", "picnic"],
     calories: 450,
     preparationTime: "15 min",
     isVegetarian: true,
     isVegan: false,
     isGlutenFree: false
   },
   {
     id: 80,
     name: "Chicken Tikka Wrap",
     price: 130,
     rating: 4.4,
     description: "Warm flatbread filled with tandoori-spiced chicken, fresh vegetables, and mint yogurt sauce.",
     category: "Sandwiches",
     imageUrl: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=480&auto=format&fit=crop",
     tags: ["indian", "wrap", "spicy"],
     calories: 520,
     preparationTime: "15 min",
     isVegetarian: false,
     isVegan: false,
     isGlutenFree: false
   },
   {
     id: 81,
     name: "Passion Fruit Mojito",
     price: 110,
     rating: 4.6,
     description: "Refreshing cocktail with white rum, fresh mint, lime, passion fruit puree, and soda water.",
     category: "Drinks",
     imageUrl: "https://images.unsplash.com/photo-1536935338788-846bb9981813?w=480&auto=format&fit=crop",
     tags: ["cocktail", "tropical", "refreshing"],
     calories: 210,
     preparationTime: "7 min",
     isVegetarian: true,
     isVegan: true,
     isGlutenFree: true
   },
   {
     id: 82,
     name: "Maple Glazed Bacon Donuts",
     price: 95,
     rating: 4.7,
     description: "Fluffy yeast donuts topped with maple glaze and crispy bacon bits for a sweet and savory treat.",
     category: "Bakery",
     imageUrl: "https://images.unsplash.com/photo-1527904324834-3bda86da6771?w=480&auto=format&fit=crop",
     tags: ["sweet and savory", "indulgent", "breakfast"],
     calories: 480,
     preparationTime: "25 min",
     isVegetarian: false,
     isVegan: false,
     isGlutenFree: false
   },
   {
     id: 83,
     name: "Kimchi Fried Rice",
     price: 130,
     rating: 4.5,
     description: "Stir-fried rice with spicy fermented kimchi, vegetables, and a sunny-side-up egg on top.",
     category: "Mains",
     imageUrl: "https://images.unsplash.com/photo-1539755530862-00f623c00e52?w=480&auto=format&fit=crop",
     tags: ["korean", "spicy", "fermented"],
     calories: 560,
     preparationTime: "20 min",
     isVegetarian: false,
     isVegan: false,
     isGlutenFree: true
   },
   {
     id: 84,
     name: "Caramelized Onion Tart",
     price: 135,
     rating: 4.4,
     description: "Buttery pastry shell filled with sweet caramelized onions, goat cheese, and fresh thyme.",
     category: "Appetizers",
     imageUrl: "https://images.unsplash.com/photo-1588166449616-3a0bb446d0a9?w=480&auto=format&fit=crop",
     tags: ["french", "savory", "vegetarian"],
     calories: 440,
     preparationTime: "35 min",
     isVegetarian: true,
     isVegan: false,
     isGlutenFree: false
   },
   {
     id: 85,
     name: "Lavender Earl Grey Latte",
     price: 85,
     rating: 4.3,
     description: "Aromatic Earl Grey tea infused with lavender, combined with steamed milk and a touch of honey.",
     category: "Drinks",
     imageUrl: "https://images.unsplash.com/photo-1577968897966-3d4325b36b61?w=480&auto=format&fit=crop",
     tags: ["tea", "aromatic", "relaxing"],
     calories: 160,
     preparationTime: "5 min",
     isVegetarian: true,
     isVegan: false,
     isGlutenFree: true
   },
   {
     id: 86,
     name: "Chimichurri Steak",
     price: 210,
     rating: 4.8,
     description: "Grilled ribeye steak topped with fresh Argentinian chimichurri sauce made with parsley, garlic, and olive oil.",
     category: "Mains",
     imageUrl: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=480&auto=format&fit=crop",
     tags: ["argentinian", "steak", "grilled"],
     calories: 680,
     preparationTime: "25 min",
     isVegetarian: false,
     isVegan: false,
     isGlutenFree: true
   },
   {
     id: 87,
     name: "Roasted Beet Hummus",
     price: 95,
     rating: 4.2,
     description: "Vibrant pink hummus made with roasted beets, chickpeas, tahini, and lemon juice, served with pita bread.",
     category: "Appetizers",
     imageUrl: "https://images.unsplash.com/photo-1553632958-1666bf30c5b3?w=480&auto=format&fit=crop",
     tags: ["vegetarian", "colorful", "healthy"],
     calories: 320,
     preparationTime: "15 min",
     isVegetarian: true,
     isVegan: true,
     isGlutenFree: true
   },
   {
     id: 88,
     name: "Orange Cardamom Creme Brûlée",
     price: 100,
     rating: 4.7,
     description: "Classic French custard dessert infused with orange zest and cardamom, topped with a caramelized sugar crust.",
     category: "Desserts",
     imageUrl: "https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?w=480&auto=format&fit=crop",
     tags: ["french", "elegant", "creamy"],
     calories: 390,
     preparationTime: "20 min",
     isVegetarian: true,
     isVegan: false,
     isGlutenFree: true
   },
   {
     id: 89,
     name: "Coconut Curry Ramen",
     price: 155,
     rating: 4.5,
     description: "Creamy coconut milk-based ramen with red curry paste, vegetables, and tofu, topped with bean sprouts and lime.",
     category: "Soups",
     imageUrl: "https://images.unsplash.com/photo-1557872943-16a5ac26437e?w=480&auto=format&fit=crop",
     tags: ["fusion", "spicy", "vegan"],
     calories: 590,
     preparationTime: "25 min",
     isVegetarian: true,
     isVegan: true,
     isGlutenFree: false
   },
   {
     id: 90,
     name: "Truffle Mac and Cheese",
     price: 165,
     rating: 4.6,
     description: "Gourmet macaroni and cheese made with a blend of artisanal cheeses, black truffle oil, and crispy breadcrumb topping.",
     category: "Mains",
     imageUrl: "https://images.unsplash.com/photo-1543352632-5a4b24e4d2a6?w=480&auto=format&fit=crop",
     tags: ["comfort food", "gourmet", "cheesy"],
     calories: 750,
     preparationTime: "30 min",
     isVegetarian: true,
     isVegan: false,
     isGlutenFree: false
   }
 ];
 

export default foodProducts;